name: Python CI with Docker + Allure + GitHub Pages + History

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: my-app:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Download previous Allure history
        run: |
          git clone --depth=1 --branch=gh-pages https://github.com/${{ github.repository }} gh-pages || true
          mkdir -p allure-results/history
          cp -r gh-pages/history/* allure-results/history/ || true

      - name: Run tests in Docker and export report
        run: docker run -v ${{ github.workspace }}/allure-results:/app/allure-results -v ${{ github.workspace }}/allure-report:/app/allure-report my-app:test

      - name: Save Allure report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  deploy-report:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          publish_dir: ./public
