name: Python Tests with Allure History

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install allure-pytest

    - name: Prepare allure history
      uses: actions/download-artifact@v4
      with:
        name: allure-history
        path: allure-report/history
        if-no-files-found: ignore

    - name: Run tests with Allure results
      env:
        PYTHONPATH: ${{ github.workspace }}/app
      run: |
        pytest tests --alluredir=allure-results

    - name: Generate Allure report with history
      run: |
        allure generate allure-results -o allure-report --clean

    - name: Upload Allure report artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report

    - name: Upload Allure history for next run
      uses: actions/upload-artifact@v3
      with:
        name: allure-history
        path: allure-report/history

    - name: Deploy Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.CI_TOKEN }}
        publish_dir: ./allure-report
